### ISSUE TITLE
any plan for wfs？

### ISSUE THREAD

**Issue by lizhongchao13** [BruTile/BruTile#110]

**Comment by pauldendulk** [comment]
No plans. Parsing WFS will mean we also need features and geometries, so this adds a lot. Libraries using this functionality would probably need to convert the BruTile geometries to their own. 

BruTile can be used for vector tiles however. The byte array returned by BruTile is then parsed to vectors in a later stage. The requests to the web service will also need to be in a specifc format so there should be a specific WPF tile source as well.
What were you thinking about? Just interested in parsing WFS or a specific tile wise request of WFS? I don't know if this is a good idea. How would that work with larger features? If you are just interested in WFS you could look at the WFS parser in Mapsui.

There is a sample for it but it is disabled because the service went down. If you know a good public WFS we could used for a sample then perhaps we could use that.
https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common.Desktop/WfsSample.cs

**Comment by lizhongchao13** [comment]
thanks for your response, i'll study BruTile and MapUI, it's helpful for me!

we are deving a gis engine using C++, contain ogc (wms、wmts、wfs) and online map，but now we are plan to dev a new map engine base CAD engine, so we should dev ogc again, but I don't want using C++ again,so I am evaluating technical proposal in .Net enviromnet. BruTile is a good sdk，but no wfs。

WFS is a common protocol standard of OGC, Maybe you should consider it.

it's difficult to download and draw large amout of feats in map real time, bad user experience，we limit 100 feats every time in fact for our user case。



At 2020-03-19 14:56:20, "Paul den Dulk" <notifications@github.com> wrote:

No plans. Parsing WFS will mean we also need features and geometries, so this adds a lot. Libraries using this functionality would probably need to convert the BruTile geometries to their own.

BruTile can be used for vector tiles however. The byte array returned by BruTile is then parsed to vectors in a later stage. The requests to the web service will also need to be in a specifc format so there should be a specific WPF tile source as well.
What were you thinking about? Just interested in parsing WFS or a specific tile wise request of WFS? I don't know if this is a good idea. How would that work with larger features? If you are just interested in WFS you could look at the WFS parser in Mapsui.

There is a sample for it but it is disabled because the service went down. If you know a good public WFS we could used for a sample then perhaps we could use that.
https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common.Desktop/WfsSample.cs

**Comment by pauldendulk** [comment]
Well, take a look the the Mapsui WFS. It has not been used in a while but it should be possible to fix that.
