### ISSUE TITLE
How to enable persistent caching on WMTS capabilities URL

### ISSUE THREAD

**Issue by Hylke-Atmos** [BruTile/BruTile#113]
Hi,

We are using the WmtsParser to recover available WMTS Tile Sources.
However it seems impossible to enable persistent caching on a selected tilesource, since you can't provide a persitent cache object with the parser.

`var tileSources = WmtsParser.Parse(httpClient.GetStreamAsync(addr).Result);`

Do you have any advice on getting this done?

**Comment by pauldendulk** [comment]
I need a bit more context. What persisten cache object are you referring to? Is this a BruTile thing or a general thing? 

Why is it it important to cache the parsed wmts. This is something you will do only once during the lifetime of the application (not saying that it is wrong, but you have to explain a bit more about what and why).

**Comment by Hylke-Atmos** [comment]
In combination with MapSui we display (multiple) different MapLayers. 
These Wmts layers (simlar to the openstreetmap en Bing layers) can contain usefull information for our users. However our users can (and often) use our application outdoors without having an internet connection.

For the Bing and Opestreetmap it is very easy to create a (local) persistent FileCache (using the "KnownTileSource.create" function:
`KnownTileSources.Create(KnownTileSource.BingAerial, persistentCache: GetPersistentCache(identifier, "EPSG:3857"))`
In the code snippet above the "GetPersistentCache()" returns a FileCache (IPersistantCache object) to cache the downloaded tiles.
This way the application can be closed and opened without internet while it is still capable of showing (parts of) the maps.

To be able to support the same strategy for Wmts steams I was looking for something similar, but was unable to find it. Currently our users must have an internet connection to be able to use Wmts map streams.

So unless I'm approaching this from a wrong perspective, I was wondering how I could cache tiles coming from a wmts streams so that they can be accessed (when no internet connection is present).

**Comment by pauldendulk** [comment]
Thanks for your clear explanation. I don't see a workaround and no easy real easy way to add this. 

I created a merge request, that I do not intend to merge, to think about this problem. It returns an HttpTileSource's from the WmtsParse. This is step in the right direction. But how to assign a cache on it? What I would prefer is to pass it to the WmtsParse method but this doesn't work because we are dealing with a list of HttpTileSources, not just one. A PersistenCache setter on the HttpTileSource might then be an alternative (although I prefer to keep it readonly). If we add a setter perhaps the internal HttpTileProvider should be removed from the HttpTileSource and it's code should be moved to the HttpTileSource, or shared some other way.

Here is the MR so you can think along:
https://github.com/BruTile/BruTile/pull/116

**Comment by Hylke-Atmos** [comment]
Thanks!

Exactly what you describe is also what has been going back and forth in my mind.
You don't want to add a setter on the persitentcache, because that should be set from construction and not be changed afterwards.
But on the other hand passing it on to the parser is also not great due to the multiple tilesources...

Just a thought:
Maybe an alternative could be to add an optional callback function to the parser that could provide a IPersistantCache object given a certain URL, Scheme, Layername or other Identifier for each TileSource?

**Comment by pauldendulk** [comment]
> Just a thought:
Maybe an alternative could be to add an optional callback function to the parser that could provide a IPersistantCache object given a certain URL, Scheme, Layername or other Identifier for each TileSource?

A just tried to envision how that would work. One thing that you see a lot in .net core is build options like [these](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.mvcjsonmvcbuilderextensions.addjsonoptions?view=aspnetcore-2.2). I thought they could maybe be used here. That would be possible but this specific case makes it a step harder because you have to find a solution to deal with multiple tilesources. This will be hard to understand for users. So I now think we should just make the PersistenCache settable. I have to think about removing the TileProvider from the HttpTileSource.

**Comment by pauldendulk** [comment]
Simply made PersistentCache settable. Had to remove the internal TileProvider. Released as 2.2.0.

**Comment by raV720** [comment]
Hi, the solution is still hard to use because we need to know the ITileSchema before we create the TileSource. Often it is a GlobalSphericalMercator but not always. How to create different ITileSchema?  When I look at WmtsCapabilitiesParser there is no method exposed to handle it.
Also when we have the TileSource we need to cache it somehow in order to restore it and use when we are offline.

**Comment by raV720** [comment]
Answering myself: just need to cache whole xml capabilites returned from WMTS endpoint. Then use it offline with the WmtsCapabilitiesParser.Parse(). Other solutions are welcome
