### ISSUE TITLE
CRS-Transformation of tiles received from WMTS

### ISSUE THREAD

**Issue by TimThaler** [BruTile/BruTile#117]
Hello,
as mentioned in https://github.com/BruTile/BruTile/issues/91 Brutile is not reprojecting tiles served  from a WMTS. I could not find any References or examples but wanted to ask if this is possible doing nowadays?
My goal is to overlay two layers. One layer's CRS is the ETRS89 (SRID 25832) while the otherone's webmercator (SRID 3857).
Overlaying them i would like to make the transformation from 25832 -> 3857 on each received tile.
Is that possible, or a different way doing that?

Best wishes,
Tim

**Comment by pauldendulk** [comment]
No, this is not supported. Also there are no plans to add this to BruTile because it would involve adding a dependency on a projection library, and I think this functionality would fit better in a Map component like Mapsui, but unfortunately Mapsui also does not support this yet. I think SharpMap does, and ArcBruTile. 

Projection of images is extra hard because in theory you need to project every pixel and then come up with an image that still looks smooth. There are algorithms that do this in a smarter way though. I think @FObermaier has used these in the past.

**Comment by PABLOCORRO** [comment]
Hello.
Overlapping two or more WMSs no transformation is required because the GetMap operation allows specifying the SRID. A common supported SRID could be selected.
I have tried to do this but Sharpmap ignores this parameter (does not send it to the server), and always uses SRID 4326. Is there a solution for overlapping WMSs?

**Comment by TimThaler** [comment]
HI @pauldendulk  thanks for your quick reply. We are currently using SharpMap. I open a similar discusson there some days ago #https://github.com/SharpMap/SharpMap/issues/186.

> Projection of images is extra hard because in theory you need to project every pixel and then come up with an image that still looks smooth

This seems indeed like a very complex topic. When rendering the Map - provided in ETRS89 - in QGIS and the change the CRS, the shape of the map changes from rectangular to a partial circular ring.

The workaround i am following now is to not overlay them, but rather switch between two map providers. While switching i transform the map center coordinates and re-set it, so that the user 
thinks he/she is in the same location. I hope the distortions are neglectable.
