### ISSUE TITLE
Create KnownTileSources with custom min/max zoom levels

### ISSUE THREAD

**Issue by janusw** [BruTile/BruTile#130]
The `GlobalSphericalMercator` class has the option of specifying minimum and maximum zoom levels, but `KnownTileSources.Create` always uses hard-wired zoom levels for all known tile sources (specific to each source).

There should be a way to create a KnownTileSource with custom zoom levels. Those custom levels still need to be cross-checked with the min/max level available for a specific source.

**Comment by pauldendulk** [comment]
So that would be another optional parameter to the KnownTileSources.Create which is then passed into the constructor of every instance. What about all the other parameters to the TileSchema? Not sure if should go that way. Perhaps something has gone wrong in the choices we made if that parameter list would only get longer over time. The idea of the known tiles sources is that it will accurately describe the source, which is a fixed thing. If a use does not want show the lowest available level this should be configured at another level. Could the MaxVisible of the Mapsui ILayer be used for that?

**Comment by FObermaier** [comment]
IMHO we should remove `KnownTileSources` and replace it with some configuration file that can be altered locally according to specific needs. I think @bertt had/has sth like this for ArcBruTile.

**Comment by janusw** [comment]
> So that would be another optional parameter to the KnownTileSources.Create which is then passed into the constructor of every instance.

That seems to be the most straightforward extension of the current structure.

> Perhaps something has gone wrong in the choices we made if that parameter list would only get longer over time. The idea of the known tiles sources is that it will accurately describe the source, which is a fixed thing. If a use does not want show the lowest available level this should be configured at another level. Could the MaxVisible of the Mapsui ILayer be used for that?

That would be nice, but it seems like those properties are currently read-only ...

**Comment by pauldendulk** [comment]
This was fixed with the PR.
