### ISSUE TITLE
Problems with TileSchema.GetTileInfos() for big extents

### ISSUE THREAD

**Issue by charlenni** [BruTile/BruTile#165]
Hello,

I have a problem when calling TileSchema.GetTileInfos() for extents greater than the `TileSchema.Extent`.

I create a TileSchema like this

    var extent = new Extent(-20037508.342789, -20037508.342789, 20037508.342789, 20037508.342789);

    var schema = new TileSchema();
    schema.Extent = _extent;
    schema.OriginX = _schema.Extent.MinX;
    schema.OriginY = _schema.Extent.MinY;

    for (var i = 0; i <= 24; i++)
    {
        schema.Resolutions.Add(i, new Resolution(i, ToResolution(i), 512, 512));
    }

Then I call `TileSchema.GetTileInfos()` with the following

    var extent = new Extent(-60538978.549791321, -26746398.822212033, 62190760.049791321, 37592788.12221203);
    var tiles = schema.GetTileInfos(extent, 0);

What I expect is one tile (0/0/0) with an Extent of `(-20037508.342789, -20037508.342789, 20037508.342789, 20037508.342789)`, because this is the only possible tile for zoom level 0. What I get is one tile (0/0/0) with an Extent of `(-20037508.342789,-20037508.342789,60112525.028367005,60112525.028367005)`. As you could see, it has a much bigger Extent than expected and far outside the limits of `TileSchema.Extent` and so not valid for the tile (0/0/0).

So the question is, what am I doing wrong while creating the TileSchema?

For testing I add a short console application: [BruTileTileSchemaProblem.zip](https://github.com/BruTile/BruTile/files/7869365/BruTileTileSchemaProblem.zip)

**Comment by pauldendulk** [comment]
The problem involves three things:
- The tile size (512, 515)
- The Resolution.UnitsPerPixel
- The Extent

Whether a top level tiles covers the entire area depends on what is specified. I can not see the values for UnitsPerPixel but I assume this is based a tile schema where a 256 tiles covers the entire area, that can not be used here. The top level Resolution for 512 should be one lower (the one with the 1 index, not 0). 

The ToResolution method is in your own code? If not we may have to fix this in BruTile.

**Comment by charlenni** [comment]
Hi Paul,

thank you for your answer. Was a dub thing to not provide the `ToResolution()` function.

    const double ScaleFactor = 78271.51696401953125;

    static double ToResolution(int level)
    {
        return 2 * ScaleFactor / (1 << level);
    }

I use it all over my project. It works for 256 and 512 tiles in the same map. So I assumed, that it should be ok. The only difference in this case is, that I create the `TileSchema` by myself. The others come from MBTiles files or via HTTP servers.

If I zoom in to zoom level 1, all works perfect.

**Comment by pauldendulk** [comment]
If you have properly generated MbTiles file with a schema based on 512, then the top resolution (the first one generated by your ToResolution method) will not be present in that MbTiles file. If you use that top resolution anyway to fetch from that MbTiles file it will not cause a problem because the closest match will be returned, which is the top tile. So, I is no surprise that the resolutions you generate there work fine if you use them in the calls to the MbTiles file. You should just not use that set of resolutions if you generate a tile schema.

The ToResolution method you show happens to be one which has 256 sized tiles in mind. It starts with a specified ScaleFactor, this is just not the correct scale factor. For practical purposes you can just take half of that value (or should it be doubled, never sure).

It would be nice if BruTile would have a helper method to generate the proper resolutions for a given tile size.

**Comment by charlenni** [comment]
Thank you for the answer.

I now changed the tile size while creating the schema from 512 to 256. Then it works. That is not totally clear for me, because even in case of 512 pixel width tiles, the created Resolutions[0] shouldn't be bigger than the Extent of the TileSchema. To get this problem nailed down, I have to download the BruTile sources and debug it. Should I do this, or is it a side case?

Up to now, I thought, that MBTiles in PBF format are always 512 pixel width. But when searching for this information, I couldn't find the information again. So I assume, that they should 256 pixel width, because they use the Google tile schema (see [here](https://github.com/mapbox/vector-tile-spec/tree/master/2.1)). Or is the pixel width only valid for displaying the tiles and up to then only extents are used?

**Comment by pauldendulk** [comment]
There is a misunderstanding. You say "the created Resolutions[0] shouldn't be bigger than the Extent of the TileSchema". That is correct, it should not be bigger. But it is bigger because you explicitly add a resolution where the top level tile does not fit! So to fix this problem you should stop adding the Resolutions[0] that is generated by the ToResolution method. ToResolution simply does not have the correct implementation for what you are trying to achieve.

Please try to understand that it is logically impossible to make a tile fit if in you code you already sets TileSize, UnitPerPixel and Extent. By setting these three values the top resolution  (the one where one tile fits the entire extent) is implicitly defined. What a BruTile helper function could do is that it would calculate the top resolution from those three values.

The MBTiles in BruTile have been built with 256 in mind. That was the specification back then. It was intended to be flexible enough to work with other tile sizes but not really tested. So sticking with 256 is the save thing to do.
