### ISSUE TITLE
Merge BruTile.Desktop.Tests projects.

### ISSUE THREAD

**Issue by FObermaier** [BruTile/BruTile#20]
For the sake of a lean solution we should merge the two BruTile.Desktop.Tests projects.
For differentiaton, we could use NUnit attributes or different namespaces.

**Comment by pauldendulk** [comment]
This was my suggestion in order to keep actual unit tests, which should always have a very precise result, separated from performance tests which have not. This in itself is not a bad idea but there might be better ways to deal with this. Perhaps we should not use unit tests at all for performance, but just a console app. Let me see if I can find some other projects with performance tests.

**Comment by pauldendulk** [comment]
Some discussion here but no consensus:
http://stackoverflow.com/questions/2870322/performance-testing-versus-unit-testing

I really don't like the idea that a unit test could have a fuzzy result. I just want it to be 100% green all the time. And with performance tests you just don't know. Even other processes on your machine could cause it to fail. I would be most happy if I was told that I should use performance framework X just like all the pro's do, so that the distinction between the two test projects would be more clear.

**Comment by FObermaier** [comment]
OK, we can leave the projects separated. In that case I propose to rename the performance project to BruTile.Performance.Desktop.

**Comment by pauldendulk** [comment]
ah yes, that is a simple and good improvement.

**Comment by FObermaier** [comment]
Done with 6c63ce35ec7f070e8329cba3195544a8669a7fb1

**Comment by pauldendulk** [comment]
Lovely
