### ISSUE TITLE
5.0.5 Version compliance with Mapsui 4.0.0

### ISSUE THREAD

**Issue by franky235** [BruTile/BruTile#216]
Hi Paul

FYI 5.0.5 is not compliant to Mapsui.Wpf 4.0.0, CreateTileLayer returns following exception: 

```console
System.MissingMethodException : 'Méthode introuvable : 'Void BruTile.Web.HttpTileSource..ctor(BruTile.ITileSchema, System.String, System.Collections.Generic.IEnumerable`1<System.String>, System.String, System.String, BruTile.Cache.IPersistentCache`1<Byte[]>, System.Func`2<System.Uri,System.Threading.Tasks.Task`1<Byte[]>>, BruTile.Attribution, System.String)'.'
```

I do not have time to investigate further at the moment
My understanding is that it could be a problem as MapsUI dependance is BruTile version >= 5.0.4 ?

**Comment by pauldendulk** [comment]
oh, I assumed that adding the optional `referer` would not make a difference to the API since it is optional, but apparently it does not work that way. So, it was a mistake to release this as a patch this way.

Options:
- Ignore: We are about to release a new Mapsui with this BruTile version. Downside: User on a lower Mapsui version will upgrade to the latest patch and will run into this error. Not great, but also we have little resources an want to move forward fast.
- Unlist this version and release it as 5.1.0. Downside: according to semver is minor upgrade should not anything either.
- Unlist this version and release it as 6.0.0. Downside: Not really necessary to do a major upgrade. But not a bad option.
- Unlist this version and release a version where the referer is added in a separate overload of the constructor. Since this is new functionality it should still be a 5.1 release since it is adding new functionality.

**Comment by franky235** [comment]
Ok, thanks for this quick reply
I choose option 1, waiting for next Mapsui version !

**Comment by janusw** [comment]
In principle unlisting would be cleaner, but if the bug reporter is ok with it, option #1 is also ok. An alternative to unlisting the package would be to revert #214 and make a bug-fix release 5.0.6 for the 'buggy' 5.0.5. Then include the breaking changes in 6.0.0 (or 5.1.0).

Regarding `HttpTileSource`, I feel like the constructor is much too bulky (more than it needs to be, and keeps getting worse). Possible options for making it simpler:
* `userAgent` and `referer` could be replaced by a `HttpClient` parameter provided by the caller. This gives the possibility for further adjustments of the header or adding credentials (if necessary), without further complication of the constructor.
* Parameters like 'name', 'persistentCache' and 'attribution' could be removed from the constructor entirely without loss of functionality, because they all can be set via public properties. So
```
new HttpTileSource(..., name: name, persistentCache: persistentCache, attribution: attribution)
```
would become
```
new HttpTileSource(...) { Name = name, PersistentCache = persistentCache, Attribution: attribution)
```

**Comment by pauldendulk** [comment]
Indeed it is. In this case I chose to add an extra parameter to keep the change small and stay in line to how it was, not aware I introduce a breaking change this way.

These days I use less constructors and use `init` properties instead. In C#11 the `required` keywords also helps. With something like this you can omit the constructor. The compiler will enforce initialization.
```csharp
public class HttpTileSource
{
    public required string Url { get; init; }
}
```

Perhaps I should release a 5.0.6 and unlist 5.0.5 and add new features as init properties.

**Comment by janusw** [comment]
> Regarding `HttpTileSource`, I feel like the constructor is much too bulky (more than it needs to be, and keeps getting worse). Possible options for making it simpler:
> 
>     * `userAgent` and `referer` could be replaced by a `HttpClient` parameter provided by the caller. This gives the possibility for further adjustments of the header or adding credentials (if necessary), without further complication of the constructor.

Actually both of them could also be set via a custom `tileFetcher` function. In that sense the extra constructor parameters are unnecessary.

Or to put it differently: When using a custom `tileFetcher`, the `userAgent` and `referer` given in the constructor will not be used.

So, it would be better to have one overload of the constructor that takes a `tileFetcher` (and possibly one with `userAgent` and `referer`) but none that takes all three parameters.

**Comment by janusw** [comment]
btw it seems that https://github.com/Mapsui/Mapsui/issues/2217 is already related to this issue

**Comment by janusw** [comment]
I actually see linker errors like this when using Mapsui 4.0 with BruTile 5.0.5 (first is iOS, second Android):
```
MTOUCH : error MT2101: Can't resolve the reference
'System.Void BruTile.Web.HttpTileSource::.ctor(BruTile.ITileSchema,System.String,System.Collections.Generic.IEnumerable`1<System.String>,System.String,System.String,BruTile.Cache.IPersistentCache`1<System.Byte[]>,System.Func`2<System.Uri,System.Threading.Tasks.Task`1<System.Byte[]>>,BruTile.Attribution,System.String)',
referenced from the method 'BruTile.Web.HttpTileSource Mapsui.Tiling.OpenStreetMap::CreateTileSource(System.String)'
in 'BruTile, Version=5.0.4.0, Culture=neutral, PublicKeyToken=null'.

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Legacy.targets(649,5):
error XALNK7000: Mono.Linker.MarkException: Error processing method:
'BruTile.Web.HttpTileSource Mapsui.Tiling.OpenStreetMap::CreateTileSource(System.String)' in assembly: 'Mapsui.Tiling.dll'
---> Mono.Cecil.ResolutionException: Failed to resolve
System.Void BruTile.Web.HttpTileSource::.ctor(BruTile.ITileSchema,System.String,System.Collections.Generic.IEnumerable`1<System.String>,System.String,System.String,BruTile.Cache.IPersistentCache`1<System.Byte[]>,System.Func`2<System.Uri,System.Threading.Tasks.Task`1<System.Byte[]>>,BruTile.Attribution,System.String)
```

... although I don't even use OpenStreetMap::CreateTileSource in my code! This is worse than I thought 😞

**Comment by pauldendulk** [comment]
Fixed with https://github.com/BruTile/BruTile/pull/221 and the release of 5.0.6. Version 5.0.5 was unlisted.

**Comment by janusw** [comment]
> Version 5.0.5 was unlisted.

I'm just thinking: Is that really a good idea? Mapsui 4.0 refers to it, doesn't it? So it might be broken by the unlisting?

**Comment by pauldendulk** [comment]
An unlisted package can still be used. Mapsui 4.0.0 is built with 5.0.4, so, that should not be a problem, but Mapsui 4.1.0 was built with 5.0.5. If users upgrade on their own behalve (which they often do, an it sometimes suggested by the tooling) they we get an error. So, we need to release a 4.1.0, but I can not do that before Monday, busy weekend is upcoming.

**Comment by janusw** [comment]
Ah, yes, you're right. Thanks for the comment.
