### ISSUE TITLE
HttpTileSource missing "referer" property in v. 5.0.6

### ISSUE THREAD

**Issue by gpsaliola** [BruTile/BruTile#222]
Hello,
In the class HttpTileSource the property "referer" is missing in the new 5.0.6 version.

```
                    HttpTileSource tileSourceXYZ = new HttpTileSource(
                        new GlobalSphericalMercator(),
                        urlFormatter: lUrl,
                        serverNodes: lServerNodes,
                        name: lName,
                        persistentCache: lDefaultCacheXYZ,
                        attribution: new BruTile.Attribution(lAttributions),
                        userAgent: lHttpValueUserAgent,
                        referer: lHttpReferer);

```

**Comment by pauldendulk** [comment]
Sorry, I intended to mention this on your earlier request, but I had to change this. It turned out it was a breaking change. I did not expect this because the parameter is optional, and it is not a breaking change if you build from code, but for compiled code it is. The method can not be found. So, I reverted that change and added an alternative: https://github.com/BruTile/BruTile/issues/213
