### ISSUE TITLE
KnownTileSource.EsriWorldDarkGrayBase - Incorrect maxZoomLevel?

### ISSUE THREAD

**Issue by ssugden** [BruTile/BruTile#33]
Hi, 

I think you have an incorrect maxZoomLevel for KnownTileSource.EsriWorldDarkGrayBase?
You have GlobalSphericalMercator(0, 10).
I think you should have GlobalSphericalMercator(0, 16)

Similarly, to avoid 404's should you not use the following?
KnownTileSource.EsriWorldPhysical - GlobalSphericalMercator(0, 8)
KnownTileSource.EsriWorldShadedRelief - GlobalSphericalMercator(0, 13)
KnownTileSource.EsriWorldReferenceOverlay - GlobalSphericalMercator(0, 13)

The other ESRI KnownTileSource's appear to be ok with the default of GlobalSphericalMercator(0, 19)

Thanks

**Comment by pauldendulk** [comment]
Thanks! I changed EsriWorldDarkGrayBase, EsriWorldPhysical and EsriWorldShadedRelief as you suggested. The changes will be in the next release.

EsriWorldReferenceOverlay is a bit different. It returns valid images all the way to lowest level but starts returning transparent images at level 10, at least in the netherlands. Did you see lower levels elsewhere?

BTW, In a future release all KnownTileSources will not be included in BruTile core but as a separate release (perhaps a code snippet) because I don't want dependencies on a specific service.

**Comment by ssugden** [comment]
I am seeing the same thing for EsriWorldReferenceOverlay. But the ESRI published info at http://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Reference_Overlay/MapServer documents 14 levels?

Thanks,

**Comment by pauldendulk** [comment]
ah, it makes sense to use the metadata as the definitive authority. I also changed EsriWorldReferenceOverlay to max 13. 

Also relevant: Mapsui has functionality for automatically parsing the esri metadata. This should be move to BruTile one day. https://github.com/pauldendulk/Mapsui/tree/master/Mapsui/Providers/ArcGIS

**Comment by ssugden** [comment]
I have been querying the ESRI MapService rest endpoint to get a json description of the map which, if it supports tiles, lists the level of details eg call http://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer?f=pjson and deserialize.

Returned json is defined here: http://services.arcgisonline.com/arcgis/sdk/rest/index.html#//02ss0000006v000000

**Comment by pauldendulk** [comment]
The best approach is indeed through the json meta data. In Mapsui this is actually already in use. See these files here: https://github.com/pauldendulk/Mapsui/tree/master/Mapsui/Providers/ArcGIS
Some day this may be moved to BruTile.
