### ISSUE TITLE
BruTile package does not work with plain .NET40

### ISSUE THREAD

**Issue by FObermaier** [BruTile/BruTile#45]
Trying to install latest BruTile nuget package (v0.18.2) to a NET40 ClientProfile project fails:
```
PM> install-package BruTile
Es wird versucht, Abhängigkeitsinformationen für das Paket "BruTile.0.18.2" bezüglich des Projekts "NuGetPackageInstall" mit dem Ziel ".NETFramework,Version=v4.0,Profile=Client" zu erfassen.
Es wird versucht, Abhängigkeiten für das Paket "BruTile.0.18.2" mit dem DependencyBehavior "Lowest" aufzulösen.
Aktionen zum Installieren des Pakets "BruTile.0.18.2" werden aufgelöst.
Aktionen zum Installieren des Pakets "BruTile.0.18.2" wurden aufgelöst.
Installationsfehler. Ein Rollback wird ausgeführt...
Das Paket "SQLite.Net.Core-PCL.3.1.0" ist im Projekt "NuGetPackageInstall" nicht vorhanden.
Das Paket "SQLite.Net.Core-PCL.3.1.0" ist im Ordner "c:\users\obe\documents\visual studio 2015\Projects\Tests\packages" nicht vorhanden.
install-package : Das Paket "SQLite.Net.Core-PCL 3.1.0" konnte nicht installiert werden. Sie versuchen, dieses Paket in ein 
Projekt zu installieren, das sich auf ".NETFramework,Version=v4.0,Profile=Client" bezieht, das Paket enthält aber keine 
Assemblyverweise oder Inhaltsdateien, die mit diesem Framework kompatibel sind. Wenden Sie sich an den Paketersteller, um 
weitere Informationen zu erhalten.
In Zeile:1 Zeichen:1
+ install-package BruTile
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by pauldendulk** [comment]
As of release [0.17.0](https://github.com/BruTile/BruTile/releases/tag/0.17.0) BruTile upgraded to PCL Profile111. This supports only .NET 4.5 and higher as mentioned in the [readme.txt](https://github.com/BruTile/BruTile/blob/master/README.md).

Options:
1. Upgrade to BruTile [0.16.0](https://github.com/BruTile/BruTile/releases/tag/0.16.0)
2. Upgrade SharpMap to .NET >= 4.5.2.

Since Microsoft stopped support for .NET versions lower than 4.5.2 (except v3.5) Januari 12 this year I think it makes sense to upgrade now. See the [Microsoft Support Lifecycle document](https://support.microsoft.com/nl-nl/lifecycle?C2=548).

**Comment by FObermaier** [comment]
The problem is the dependency on SqLite.PCL which is marked as required.
It should be wrapped in a `<group>` node.

**Comment by pauldendulk** [comment]
Right, there is still the BruTile version compiled to .NET 4.0 proper. So this could be fixed with <group> but I would prefer to fix it with a separate NuGet package for the MBTiles provider. This was the orginal plan but I did not have time for it on that particular night. So, I could do that... but much rather I would like to forget about .NET 4.0 altogether. There is much new stuff coming up. .NET Core, everything Xamarin related. Why invest in a .NET version that is not supported anymore?

**Comment by FObermaier** [comment]
A sepearte package for the PCL MB-Tiles provider?

In general I agree with you but I would not ditch support for .NET40 as long as the code compiles without having to invest much.

NTS/GeoAPI still serves .NET20 assemblies and so do other popular packages like e.g. Newtonsoft.Json.

**Comment by pauldendulk** [comment]
Yes, primarily because of the dependency on SQLite. Also to keep BruTile core super simple. I like super simple. 

Supporting 2.0 and 4.0 is an investment. Not so much in the work you have to do but it is an extra complication. It makes everything a bit more complicated. It is an extra thing to think about whenever you want to make changes. The fact that this issue exists is proof of that.
