### ISSUE TITLE
Bug: can´t compute GPS position from pixel position in wmts and partial map source

### ISSUE THREAD

**Issue by BuFran** [BruTile/BruTile#66]
Hi, @pauldendulk  I should report long-present bug in BruTile. In version 0.18.1 in sha: 7a336e9df27dca23a6aae4a521b30c08e160c4b9 you are introduced an bug in BruTile. You swapped two params in declaration of Resolution, but you did not distributed those changes to other places, so computation of GPS coordinates from XY pixel positions on map sources are wrong if map sources are small, not covering entire planet. It was correct until this commit.

It needs to change in wmtsParser.cs to switch values on lines 353 and 355 too, because the order is in wmts defined in the old order (before the 0.18.1), or to revert all changes made by this commit.

Maybe the change propagated this bug somewhere else too, but I found it only on wmts, because I use only this service. It should be proven what correction will fit best.

It can be simply tested on maps of Czech Republic  from:

http://geoportal.cuzk.cz/WMTS_ZABAGED/WMTService.aspx?service=WMTS&request=GetCapabilities

(I have some modifications to support this service, Capabilities are not well-parsed by BruTile, I can post some MergeRequests later if you like to completely support this service)

**Comment by pauldendulk** [comment]
Thanks for the report. The change in coordinate order was itself a bugfix. I have to dig into to this to figure out what was going on there. 

Merge requests with respect to capability parsing are welcome.

**Comment by pauldendulk** [comment]
A lot of changes were made since the commit you pointed to. The coordinate order issue has been a complicated one. We have been struggling with that.  The commit itself is correct. It seems the order of the parameters is passed in correctly, although that is hard to judge given that it can differ between between coordinate systems.

I added a unit test for the capabilities you provided.  It turned out that there were two issues on which the parser failed. I fixed them in the commits you can see referenced above. If I test  it in this form in Mapsui it look correct to me. The coordinate in Mapsui are also correct when hovering above Prague.

**Comment by pauldendulk** [comment]
I released a new version. Perhaps you can check if your problem persists:
https://www.nuget.org/packages/BruTile/0.22.2

**Comment by pauldendulk** [comment]
I am closing this. As far as I know this is fixed with the latest release. Please reopen when it does not work for you.
