### ISSUE TITLE
Defective project file ... ?

### ISSUE THREAD

**Issue by JoeCooper** [BruTile/BruTile#67]
When I try to open the solution, the "BruTile" project fails to load due to an error: "Error while trying to load the project '.../BruTile/BruTile.csproj': Project does not support framework '.NETPortable,Version=4.5,Profile=Profile111'. This is in Visual Studio for Mac 7.1 build 1297.

I looked at the .csproj file and found the ProjectTypeGuids were commented out.

When I uncomment this line, it works perfectly. Loads & builds.

What's the story behind this?

**Comment by pauldendulk** [comment]
This was changed in [this commit](https://github.com/BruTile/BruTile/commit/9a741a2e1847ab9a5b8e6f1f1646bf9686f50fd7). The commit message says: 'Making WmsCapabilities.cs file Net35 compatible'. Since we no longer support Net35, only PCL111, this change is not relevant anymore and could be changed back.

In Visual Studio this change causes no problem.

**Comment by JoeCooper** [comment]
All clear. I understand it's not necessary anymore. Because it is causing issues in the IDE formerly known as Xamarin, I've undone this tweak and the change is in my fork.
